# Generated by Django 5.0.9 on 2024-09-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_recipe_recipecomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="status",
            field=models.CharField(
                choices=[("DF", "Draft"), ("PB", "Published")],
                default="DF",
                max_length=2,
            ),
        ),
    ]
