# Generated by Django 5.0.9 on 2024-09-17 00:30

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_recipe_status"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["-publish"]},
        ),
        migrations.RemoveIndex(
            model_name="recipe",
            name="blog_recipe_created_85a62b_idx",
        ),
        migrations.AddField(
            model_name="recipe",
            name="publish",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["-publish"], name="blog_recipe_publish_8268d9_idx"
            ),
        ),
    ]
