# Generated by Django 5.1.1 on 2024-09-17 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="publish"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="recipecomment",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.recipe",
            ),
        ),
    ]
